/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crazycdn_gvryssdk_VrVideoRenderer */

#ifndef _Included_com_crazycdn_gvryssdk_VrVideoRenderer
#define _Included_com_crazycdn_gvryssdk_VrVideoRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeCreate
 * Signature: (Ljava/lang/ClassLoader;Ljava/lang/Object;F)J
 */
JNIEXPORT jlong JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeCreate
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeResize
 * Signature: (JIIFFI)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeResize
  (JNIEnv *, jobject, jlong, jint, jint, jfloat, jfloat, jint);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeRenderFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeRenderFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeSetStereoMode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeSetStereoMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeSetPureTouchTracking
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeSetPureTouchTracking
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeOnPause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeOnPause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeOnResume
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeOnResume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeOnPanningEvent
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeOnPanningEvent
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeGetHeadRotation
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeGetHeadRotation
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeSetSphericalMetadata
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeSetSphericalMetadata
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeSetVideoTexture
 * Signature: (J[I)J
 */
JNIEXPORT jlong JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeSetVideoTexture
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_crazycdn_gvryssdk_VrVideoRenderer
 * Method:    nativeSetCameraRotation
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_crazycdn_gvryssdk_VrVideoRenderer_nativeSetCameraRotation
  (JNIEnv *, jobject, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
